### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by annevk** [intarchboard/protocol-maintenance#7]
I still think it's worth touching on extensibility in the error handling section. E.g., if HTTP clients all rejected responses with status codes that are not registered rather than falling back to the default for the range, it'd be much harder to introduce a new status code.

**Comment by martinthomson** [comment]
But that is precisely defined in the HTTP spec, and so isn't at all unspecified or unusual.  What would be unusual would be a 765 status code or a status code of "octopus".  Those likely fall into the general bucket of things that a client implementation might do in the name of "message handling robustness.  Or, as suggested here, errors.

**Comment by annevk** [comment]
Well, e.g., 450 might gain some additional meaning going forward. So producers best avoid it until such a time it actually is specified and implemented and until then it'd be considered an error of sorts for them to generate it. Consumers best handle it identically to 400 until such a time it's defined as that's more forward-compatible than hard failing.

**Comment by martinthomson** [comment]
Hmm, that doesn't seem like an application of the robustness principle, just following the general rule of don't send something that you don't know the meaning of.

**Comment by annevk** [comment]
The main reason I'm raising it is because these classes of errors are often conflated and different standardization communities also them differently.

And it's not just about the producer, it's about legacy receivers too. I'm more comfortable sending 450 if I know it won't result in a consumer error for older consumers.

Or if you have some JSON format it's often better to ignore unknown fields than to validate the entire JSON structure and reject on unknowns. Assuming you want to extend in a way that is backwards compatible and degrades gracefully.

That nuance is often missing when folks complain about things not being "strict".

**Comment by martinthomson** [comment]
I think that I got this one.
